# Generated by Django 4.2.7 on 2025-12-08 00:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='aliModel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('lb_id', models.IntegerField(null=True, verbose_name='负载均衡实例ID')),
                ('lb_name', models.CharField(max_length=255, null=True, verbose_name='负载均衡实例名称')),
                ('lb_status', models.CharField(max_length=255, null=True, verbose_name='负载均衡实例状态')),
                ('lb_address', models.CharField(max_length=255, null=True, verbose_name='负载均衡实例ip地址')),
                ('lb_type', models.CharField(max_length=255, null=True, verbose_name='负载均衡实例类型')),
                ('lb_region', models.CharField(max_length=255, null=True, verbose_name='负载均衡实例地域')),
                ('lb_bandwidth', models.IntegerField(null=True, verbose_name='负载均衡实例带宽')),
            ],
        ),
    ]
