# Generated by Django 4.2.7 on 2025-12-12 01:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LoadBalancer',
            fields=[
                ('LoadBalancerId', models.CharField(max_length=50, primary_key=True, serialize=False, verbose_name='负载均衡ID')),
                ('LoadBalancerName', models.CharField(max_length=255, verbose_name='负载均衡名称')),
                ('Address', models.GenericIPAddressField(verbose_name='服务地址')),
                ('AddressIPVersion', models.CharField(choices=[('ipv4', 'IPv4'), ('ipv6', 'IPv6')], max_length=10, verbose_name='IP版本')),
                ('AddressType', models.CharField(choices=[('internet', '公网'), ('intranet', '内网')], max_length=20, verbose_name='地址类型')),
                ('NetworkType', models.CharField(choices=[('classic', '经典网络'), ('vpc', '专有网络')], max_length=20, verbose_name='网络类型')),
                ('RegionId', models.CharField(max_length=50, verbose_name='地域ID')),
                ('RegionIdAlias', models.CharField(max_length=50, verbose_name='地域别名')),
                ('MasterZoneId', models.CharField(max_length=50, verbose_name='主可用区')),
                ('SlaveZoneId', models.CharField(max_length=50, verbose_name='备可用区')),
                ('VpcId', models.CharField(blank=True, max_length=50, null=True, verbose_name='VPC ID')),
                ('VSwitchId', models.CharField(blank=True, max_length=50, null=True, verbose_name='虚拟交换机ID')),
                ('Bandwidth', models.IntegerField(verbose_name='带宽(Mbps)')),
                ('LoadBalancerSpec', models.CharField(max_length=50, verbose_name='规格')),
                ('InstanceChargeType', models.CharField(max_length=20, verbose_name='实例计费类型')),
                ('InternetChargeType', models.CharField(max_length=20, verbose_name='公网计费类型')),
                ('InternetChargeTypeAlias', models.CharField(max_length=50, verbose_name='公网计费类型别名')),
                ('PayType', models.CharField(max_length=20, verbose_name='付费类型')),
                ('LoadBalancerStatus', models.CharField(max_length=50, verbose_name='状态')),
                ('DeleteProtection', models.CharField(choices=[('on', '开启'), ('off', '关闭')], max_length=10, verbose_name='删除保护')),
                ('ResourceGroupId', models.CharField(max_length=50, verbose_name='资源组ID')),
                ('CreateTime', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('UpdateTime', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '阿里云负载均衡',
                'db_table': 'aliyun_load_balancer',
            },
        ),
        migrations.CreateModel(
            name='SLBListener',
            fields=[
                ('listener_id', models.CharField(max_length=100, primary_key=True, serialize=False, verbose_name='监听器ID')),
                ('listener_port', models.IntegerField(verbose_name='监听端口')),
                ('backend_server_port', models.IntegerField(verbose_name='后端端口')),
                ('listener_protocol', models.CharField(max_length=20, verbose_name='监听协议')),
                ('scheduler', models.CharField(max_length=20, verbose_name='调度算法')),
                ('bandwidth', models.IntegerField(verbose_name='带宽峰值(Mbps)')),
                ('status', models.CharField(max_length=20, verbose_name='状态')),
                ('acl_status', models.CharField(max_length=10, verbose_name='访问控制状态')),
                ('description', models.CharField(blank=True, max_length=255, null=True, verbose_name='描述')),
                ('tcp_listener_config', models.JSONField(default=dict, verbose_name='TCP监听器配置')),
                ('http_listener_config', models.JSONField(default=dict, verbose_name='HTTP监听器配置')),
                ('established_timeout', models.IntegerField(verbose_name='TCP连接保持时间(秒)')),
                ('health_check', models.CharField(max_length=10, verbose_name='健康检查状态')),
                ('health_check_connect_timeout', models.IntegerField(verbose_name='TCP连接保持超时时间(秒)')),
                ('health_check_domain', models.CharField(blank=True, max_length=255, null=True, verbose_name='健康检查域名')),
                ('health_check_http_code', models.CharField(blank=True, max_length=255, null=True, verbose_name='健康检查HTTP状态码')),
                ('health_check_interval', models.IntegerField(verbose_name='健康检查间隔时间(秒)')),
                ('health_check_type', models.CharField(max_length=20, verbose_name='健康检查类型')),
                ('health_check_uri', models.CharField(blank=True, max_length=255, null=True, verbose_name='健康检查URI')),
                ('healthy_threshold', models.IntegerField(verbose_name='健康检查成功次数')),
                ('persistence_timeout', models.IntegerField(verbose_name='会话保持超时时间(秒)')),
                ('proxy_protocol_v2_enabled', models.CharField(max_length=10, verbose_name='Proxy Protocol V2状态')),
                ('unhealthy_threshold', models.IntegerField(verbose_name='健康检查失败次数')),
                ('https_listener_config', models.JSONField(default=dict, verbose_name='HTTPS监听器配置')),
                ('udp_listener_config', models.JSONField(default=dict, verbose_name='UDP监听器配置')),
                ('tags', models.JSONField(default=list, verbose_name='标签')),
                ('request_id', models.CharField(blank=True, max_length=100, null=True, verbose_name='请求ID')),
                ('total_count', models.IntegerField(default=0, verbose_name='总记录数')),
                ('max_results', models.IntegerField(default=20, verbose_name='每页最大结果数')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('LoadBalancerId', models.ForeignKey(db_column='load_balancer_id', on_delete=django.db.models.deletion.CASCADE, related_name='listeners', to='api.loadbalancer', verbose_name='所属负载均衡')),
            ],
            options={
                'verbose_name': '负载均衡监听器',
                'db_table': 'slb_listener',
            },
        ),
        migrations.DeleteModel(
            name='aliModel',
        ),
    ]
