# Generated by Django 4.2.7 on 2026-01-09 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_txalbmodels_delete_albcertificate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='txalbmodels',
            name='RequestId',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='请求ID'),
        ),
    ]
