# Generated by Django 4.2.7 on 2026-01-09 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_txalbmodels_requestid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='txalbmodels',
            name='BackupZoneSet',
            field=models.JSONField(blank=True, default=list, null=True, verbose_name='备可用区集合'),
        ),
        migrations.AlterField(
            model_name='txalbmodels',
            name='MasterZone',
            field=models.JSONField(blank=True, default=dict, null=True, verbose_name='主可用区'),
        ),
    ]
