# Generated by Django 4.2.7 on 2026-01-09 12:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_txalbmodels_backupzoneset_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TxListenerModel',
            fields=[
                ('ListenerId', models.CharField(max_length=100, primary_key=True, serialize=False, verbose_name='监听器ID')),
                ('ListenerName', models.CharField(blank=True, default='', max_length=200, verbose_name='监听器名称')),
                ('Protocol', models.CharField(default='HTTP', max_length=20, verbose_name='协议类型')),
                ('Port', models.IntegerField(default=80, verbose_name='监听端口')),
                ('EndPort', models.IntegerField(default=0, verbose_name='结束端口（端口段）')),
                ('Scheduler', models.CharField(blank=True, max_length=50, null=True, verbose_name='调度算法')),
                ('SessionExpireTime', models.IntegerField(blank=True, null=True, verbose_name='会话保持时间')),
                ('SniSwitch', models.IntegerField(default=0, verbose_name='SNI开关')),
                ('SessionType', models.CharField(default='NORMAL', max_length=50, verbose_name='会话类型')),
                ('KeepaliveEnable', models.IntegerField(default=0, verbose_name='长连接开关')),
                ('Toa', models.BooleanField(default=False, verbose_name='TOA开关')),
                ('DeregisterTargetRst', models.BooleanField(default=False, verbose_name='解绑目标时重置')),
                ('MaxConn', models.IntegerField(default=-1, verbose_name='最大连接数')),
                ('MaxCps', models.IntegerField(default=-1, verbose_name='每秒新建连接数')),
                ('IdleConnectTimeout', models.IntegerField(blank=True, null=True, verbose_name='空闲超时时间')),
                ('RescheduleInterval', models.IntegerField(blank=True, null=True, verbose_name='重调度间隔')),
                ('RescheduleStartTime', models.DateTimeField(blank=True, null=True, verbose_name='重调度开始时间')),
                ('DataCompressMode', models.CharField(default='transparent', max_length=50, verbose_name='数据压缩模式')),
                ('AttrFlags', models.JSONField(default=list, verbose_name='属性标志')),
                ('QuicStatus', models.CharField(default='QUIC_INACTIVE', max_length=50, verbose_name='QUIC状态')),
                ('Http2', models.BooleanField(default=False, verbose_name='HTTP/2开关')),
                ('HttpGzip', models.BooleanField(default=False, verbose_name='HTTP Gzip压缩')),
                ('CreateTime', models.DateTimeField(verbose_name='创建时间')),
                ('CertificateInfo', models.JSONField(blank=True, null=True, verbose_name='证书信息')),
                ('HealthCheckInfo', models.JSONField(blank=True, null=True, verbose_name='健康检查配置')),
                ('TargetType', models.CharField(blank=True, max_length=50, null=True, verbose_name='目标类型')),
                ('TargetGroup', models.JSONField(blank=True, null=True, verbose_name='目标组')),
                ('TargetGroupList', models.JSONField(blank=True, null=True, verbose_name='目标组列表')),
                ('WafDomainId', models.CharField(blank=True, default='', max_length=100, verbose_name='WAF域名ID')),
                ('TrpcCallee', models.CharField(blank=True, default='', max_length=200, verbose_name='TRPC被调方')),
                ('TrpcFunc', models.CharField(blank=True, default='', max_length=200, verbose_name='TRPC函数名')),
                ('OAuthInfo', models.JSONField(blank=True, null=True, verbose_name='OAuth配置')),
                ('CookieName', models.CharField(blank=True, default='', max_length=200, verbose_name='会话保持Cookie名称')),
                ('RequestId', models.CharField(blank=True, default='', max_length=100, verbose_name='请求ID')),
                ('BeAutoCreated', models.BooleanField(default=False, verbose_name='是否自动创建')),
                ('DefaultServer', models.BooleanField(default=False, verbose_name='是否是默认服务器')),
                ('LoadBalancer', models.ForeignKey(db_column='LoadBalancerId', on_delete=django.db.models.deletion.CASCADE, related_name='listeners', to='api.txalbmodels', verbose_name='关联负载均衡')),
            ],
            options={
                'verbose_name': '腾讯云监听器',
                'db_table': 'tx_listener',
            },
        ),
    ]
