# Generated by Django 4.2.7 on 2026-01-12 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_txlistenermodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='UcloudULBModels',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Bandwidth', models.IntegerField(max_length=50, verbose_name='带宽')),
                ('BandwidthType', models.CharField(default='PayByTraffic', max_length=50, verbose_name='带宽类型')),
                ('BusinessId', models.CharField(blank=True, default='', max_length=100, verbose_name='业务组ID')),
                ('CreateTime', models.CharField(max_length=50, verbose_name='创建时间')),
                ('EnableLog', models.BooleanField(max_length=50, verbose_name='是否开启日志')),
                ('FirewallSet', models.JSONField(max_length=50, verbose_name='防火墙配置')),
                ('IPSet', models.JSONField(max_length=50, verbose_name='IP配置')),
                ('IPVersion', models.CharField(default='IPv4', max_length=50, verbose_name='IP版本')),
                ('ListenType', models.CharField(choices=[('RequestProxy', '请求代理'), ('PacketsTransmit', '报文转发'), ('ServerMode', '服务器模式')], max_length=50, verbose_name='监听类型')),
                ('LogSet', models.JSONField(verbose_name='日志配置')),
                ('Name', models.CharField(max_length=100, verbose_name='名称')),
                ('PrivateIP', models.CharField(blank=True, default='', max_length=100, verbose_name='内网IP')),
                ('Remark', models.CharField(blank=True, default='', max_length=500, verbose_name='备注')),
                ('Resource', models.JSONField(max_length=50, verbose_name='资源信息')),
                ('SnatIps', models.JSONField(max_length=50, verbose_name='NAT网关IP')),
                ('SubnetId', models.CharField(blank=True, default='', max_length=100, verbose_name='子网ID')),
                ('Tag', models.JSONField(max_length=50, verbose_name='标签')),
                ('ULBId', models.CharField(db_index=True, max_length=100, unique=True, verbose_name='ULB ID')),
                ('ULBType', models.CharField(choices=[('OuterMode', '外网模式'), ('InnerMode', '内网模式')], default='OuterMode', max_length=20, verbose_name='ULB类型')),
                ('VPCId', models.CharField(blank=True, default='', max_length=100, verbose_name='VPC ID')),
                ('VServerSet', models.JSONField(max_length=50, verbose_name='VServer配置')),
            ],
            options={
                'verbose_name': 'ULB负载均衡器',
            },
        ),
        migrations.CreateModel(
            name='VServer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('BackendSet', models.JSONField(max_length=50, verbose_name='后端服务器组')),
                ('ClientTimeout', models.IntegerField(max_length=50, verbose_name='客户端超时时间')),
                ('Domain', models.CharField(blank=True, default='', max_length=100, verbose_name='域名')),
                ('EnableCompression', models.BooleanField(max_length=50, verbose_name='是否开启压缩')),
                ('EnableHTTP2', models.BooleanField(max_length=50, verbose_name='是否开启HTTP2')),
                ('ForwardPort', models.IntegerField(max_length=50, verbose_name='转发端口')),
                ('FrontendPort', models.IntegerField(max_length=50, verbose_name='前端端口')),
                ('ListenType', models.CharField(choices=[('RequestProxy', '请求代理'), ('PacketsTransmit', '报文转发'), ('ServerMode', '服务器模式')], default='RequestProxy', max_length=20, verbose_name='监听类型')),
                ('Method', models.CharField(choices=[('Roundrobin', '轮询'), ('Source', '源地址'), ('Weight', '加权轮询'), ('LeastConn', '最少连接')], default='Roundrobin', max_length=20, verbose_name='调度算法')),
                ('MonitorType', models.CharField(choices=[('Port', '端口'), ('Path', '路径'), ('Ping', 'Ping')], default='Port', max_length=20, verbose_name='监控类型')),
                ('Path', models.CharField(blank=True, default='', max_length=100, verbose_name='路径')),
                ('PersistenceInfo', models.JSONField(max_length=50, verbose_name='会话保持信息')),
                ('PersistenceType', models.CharField(choices=[('None', '无'), ('UserDefined', '用户自定义'), ('ServerInsert', '服务器插入'), ('AutoGenerated', '自动生成')], default='None', max_length=20, verbose_name='会话保持类型')),
                ('PolicySet', models.JSONField(max_length=50, verbose_name='策略组')),
            ],
            options={
                'verbose_name': '监听器',
            },
        ),
    ]
