# Generated by Django 4.2.7 on 2026-01-12 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_ucloudulbmodels_vserver'),
    ]

    operations = [
        migrations.CreateModel(
            name='UcloudNlbModels',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NlbId', models.CharField(db_index=True, max_length=100, unique=True, verbose_name='nlbid')),
                ('Name', models.CharField(max_length=100, verbose_name='名称')),
                ('Tag', models.CharField(max_length=50, verbose_name='标签')),
                ('Remark', models.CharField(blank=True, default='', max_length=500, verbose_name='备注')),
                ('IPVersion', models.CharField(default='IPv4', max_length=50, verbose_name='IP版本')),
                ('SubnetId', models.CharField(blank=True, default='', max_length=100, verbose_name='子网ID')),
                ('IPInfos', models.JSONField(max_length=50, verbose_name='IP信息')),
                ('ForwardingMode', models.CharField(max_length=50, verbose_name='转发模式')),
                ('ChargeType', models.CharField(default='PostPaid', max_length=50, verbose_name='计费方式')),
                ('CreateTime', models.CharField(max_length=50, verbose_name='创建时间')),
                ('PurchaseValue', models.IntegerField(max_length=50, verbose_name='购买时长')),
                ('Listeners', models.JSONField(max_length=50, verbose_name='监听器')),
                ('Status', models.CharField(max_length=50, verbose_name='状态')),
                ('AutoRenewEnabled', models.BooleanField(default=False, verbose_name='是否自动续费')),
                ('DeletionProtection', models.BooleanField(default=False, verbose_name='是否开启删除保护')),
            ],
            options={
                'verbose_name': 'UcloudNLB',
            },
        ),
    ]
