# Generated by Django 4.2.7 on 2026-01-12 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_ucloudnlbmodels'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ucloudnlbmodels',
            name='Listeners',
            field=models.JSONField(blank=True, max_length=50, verbose_name='监听器'),
        ),
    ]
