# Generated by Django 4.2.7 on 2026-01-12 06:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_alter_ucloudnlbmodels_listeners'),
    ]

    operations = [
        migrations.CreateModel(
            name='UcloudNlbListenerModels',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ListenerId', models.CharField(db_index=True, max_length=100, unique=True, verbose_name='listenerid')),
                ('Name', models.CharField(max_length=100, verbose_name='名称')),
                ('remark', models.CharField(blank=True, default='', max_length=500, verbose_name='备注')),
                ('StartPort', models.IntegerField(max_length=50, verbose_name='开始端口')),
                ('EndPort', models.IntegerField(max_length=50, verbose_name='结束端口')),
                ('Protocol', models.CharField(max_length=50, verbose_name='协议')),
                ('Scheduler', models.CharField(max_length=50, verbose_name='调度算法')),
                ('StickinessTimeout', models.IntegerField(max_length=50, verbose_name='会话保持超时时间')),
                ('ForwardSrcIPMethod', models.CharField(max_length=50, verbose_name='转发源IP方式')),
                ('HealthCheckConfig', models.JSONField(max_length=50, verbose_name='健康检查配置')),
                ('Targets', models.JSONField(max_length=50, verbose_name='后端服务器组')),
                ('State', models.CharField(max_length=50, verbose_name='状态')),
                ('DeletionProtection', models.BooleanField(default=False, verbose_name='是否开启删除保护')),
                ('NLBId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.ucloudnlbmodels')),
            ],
            options={
                'verbose_name': 'UcloudNLB监听器',
            },
        ),
    ]
