# Generated by Django 4.2.7 on 2026-01-12 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_ucloudnlblistenermodels'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ucloudnlblistenermodels',
            name='Targets',
            field=models.JSONField(blank=True, max_length=50, null=True, verbose_name='后端服务器组'),
        ),
    ]
