# Generated by Django 4.2.7 on 2026-01-12 06:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_alter_ucloudnlblistenermodels_targets'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ucloudnlblistenermodels',
            name='NLBId',
            field=models.ForeignKey(db_column='NlbId', on_delete=django.db.models.deletion.CASCADE, related_name='listeners', to='api.ucloudnlbmodels', to_field='NlbId'),
        ),
    ]
